<template><div><p>從<a href="http://fontello.com/" target="_blank" rel="noopener noreferrer">http://fontello.com/</a>下載font icon，zip檔入面有demo.html，列出如何使用fontello icon ，我的目的是利Nokogiri在rake task以ruby list 形式列印出所有class name，以下是該rake task的程式碼 :</p>
<div class="language-ruby line-numbers-mode" data-highlighter="prismjs" data-ext="rb"><pre v-pre><code class="language-ruby"><span class="line">namespace <span class="token symbol">:dev</span> <span class="token keyword">do</span></span>
<span class="line">  task <span class="token symbol">:font_icon_list</span> <span class="token keyword">do</span></span>
<span class="line">    text <span class="token operator">=</span> open<span class="token punctuation">(</span>Rails<span class="token punctuation">.</span>root<span class="token punctuation">.</span>join<span class="token punctuation">(</span><span class="token string-literal"><span class="token string">'doc'</span></span><span class="token punctuation">,</span> <span class="token string-literal"><span class="token string">'fontello-c340d124'</span></span><span class="token punctuation">,</span><span class="token string-literal"><span class="token string">'demo.html'</span></span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span>read</span>
<span class="line">    html_doc <span class="token operator">=</span> Nokogiri<span class="token double-colon punctuation">::</span><span class="token constant">HTML</span><span class="token punctuation">(</span>text<span class="token punctuation">)</span></span>
<span class="line">    font_icon_list <span class="token operator">=</span> html_doc<span class="token punctuation">.</span>xpath<span class="token punctuation">(</span><span class="token string-literal"><span class="token string">%{//div[@class="row"]//div//span[@class="i-name"]//text()}</span></span><span class="token punctuation">)</span></span>
<span class="line">    font_icon_list_code <span class="token operator">=</span> <span class="token operator">%</span><span class="token punctuation">{</span><span class="token punctuation">[</span><span class="token string-literal"><span class="token string">"</span><span class="token interpolation"><span class="token delimiter punctuation">#{</span><span class="token content">font_icon_list<span class="token punctuation">.</span>to_a<span class="token punctuation">.</span>join<span class="token punctuation">(</span><span class="token string-literal"><span class="token string">%{","}</span></span><span class="token punctuation">)</span></span><span class="token delimiter punctuation">}</span></span><span class="token string">"</span></span><span class="token punctuation">]</span><span class="token punctuation">}</span></span>
<span class="line">    puts font_icon_list_code</span>
<span class="line">  <span class="token keyword">end</span></span>
<span class="line"><span class="token keyword">end</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>最後執行rake task輸出結果</p>
<div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh"><pre v-pre><code class="language-bash"><span class="line">rake dev:font_icon_list <span class="token operator">></span> result.txt</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div></div></template>


